-- AlterTable
ALTER TABLE `StoreSettings`
    ADD COLUMN `mailFrom` VARCHAR(191) NULL,
    ADD COLUMN `mailFromName` VARCHAR(191) NULL,
    ADD COLUMN `storeBaseUrl` VARCHAR(191) NULL,
    ADD COLUMN `adminBaseUrl` VARCHAR(191) NULL,
    ADD COLUMN `senderName` VARCHAR(191) NULL,
    ADD COLUMN `senderPhone` VARCHAR(191) NULL,
    ADD COLUMN `senderEmail` VARCHAR(191) NULL,
    ADD COLUMN `senderDocument` VARCHAR(191) NULL,
    ADD COLUMN `senderAddress` VARCHAR(191) NULL,
    ADD COLUMN `senderNumber` VARCHAR(191) NULL,
    ADD COLUMN `senderComplement` VARCHAR(191) NULL,
    ADD COLUMN `senderDistrict` VARCHAR(191) NULL,
    ADD COLUMN `senderCity` VARCHAR(191) NULL,
    ADD COLUMN `senderState` VARCHAR(191) NULL,
    ADD COLUMN `storeZipCode` VARCHAR(191) NULL,
    ADD COLUMN `storeWeight` VARCHAR(191) NULL,
    ADD COLUMN `storeLength` VARCHAR(191) NULL,
    ADD COLUMN `storeWidth` VARCHAR(191) NULL,
    ADD COLUMN `storeHeight` VARCHAR(191) NULL,
    ADD COLUMN `pixKey` VARCHAR(191) NULL,
    ADD COLUMN `pixMerchantName` VARCHAR(191) NULL,
    ADD COLUMN `pixMerchantCity` VARCHAR(191) NULL;
